# Generated by Django 4.2.20 on 2025-04-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
