# Generated by Django 4.2.21 on 2025-05-21 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_name', models.TextField()),
                ('workspace_desc', models.TextField()),
                ('workspace_related_users', models.ManyToManyField(related_name='workspaces', to='Todo.userregistration')),
            ],
        ),
    ]
