# Generated by Django 4.2.21 on 2025-05-21 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
