# Generated by Django 4.2.20 on 2025-04-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_userregistration_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='user_password',
            new_name='password',
        ),
    ]
